# Generated by Django 5.1.2 on 2024-10-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ageRestrictionsID',
            new_name='agerestrictions',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='animationFormatID',
            new_name='animationformat',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movieGenreID',
            new_name='moviegenre',
        ),
        migrations.RenameField(
            model_name='moviesession',
            old_name='seatID',
            new_name='seat',
        ),
        migrations.RenameField(
            model_name='moviesession',
            old_name='ticketID',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='showtime',
            old_name='movieID',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='showtime',
            old_name='roomID',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='showtimeID',
            new_name='showtime',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='viewerID',
            new_name='viewer',
        ),
    ]
